apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.pageConfigMapName" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    {{- include "webapp.pageHtml" . | nindent 4 }}
